#!/bin/bash


nested_directories="
    ${HOME}/Code
    /shared/Code
"

directories="
    ${HOME}/Documents
    ${HOME}/Documents/Work
"
projects=$(find ${directories} -maxdepth 1 -type d 2> /dev/null)
nested_projects=$(find ${nested_directories} -mindepth 2 -maxdepth 2 -type d 2> /dev/null)

#exit on error, but only after find
# set -e 

combined="${projects}
${nested_projects}"

selected=$(printf '%s\n' ${combined} | fzf)

name=$(basename ${selected})
replaced_name=$(echo ${name} | sed 's/\./_/g')

if ! tmux has-session -t "${replaced_name}" 2> /dev/null; then
    tmux new-session -c "${selected}" -s "${replaced_name}" -d
fi

if [[ -z $TMUX ]]; then
    tmux attach -t "${replaced_name}"
else
    tmux switch -t "${replaced_name}"
fi
