#!/bin/bash

set -e #exit on error

nested_directories="
    ${HOME}/Code
    /shared/Code
"

directories="
    ${HOME}/Documents
    ${HOME}/Documents/Work
"
projects=$(find ${directories} -maxdepth 1 -type d 2> /dev/null)
nested_projects=$(find ${nested_directories} -mindepth 2 -maxdepth 2 -type d 2> /dev/null)

combined="${projects}
${nested_projects}"

selected=$(printf '%s\n' ${combined} | fzf)

name=$(basename ${selected})

tmux new-session -c "${selected}" -s "${name}" -d
